### ISSUE TITLE
wrong path in /etc/php5/fpm/conf.d/20-xdebug.ini

### ISSUE THREAD

**Issue by lucymtc** [Automattic/vip-quickstart#485]
Having some trouble enabling Xdebug. Thorsten Ott found out the path in /etc/php5/fpm/conf.d/20-xdebug.ini was wrong.

After typing in  
`root@vip:/etc/php5# php`

`Failed loading /usr/lib/php5/20090626+lfs/xdebug.so:  /usr/lib/php5/20090626+lfs/xdebug.so: cannot open shared object file: No such file or directory`

Find out the correct path with:
`ls /usr/lib/php5/`

Then search replace:
`sed 's/20090626+lfs/20131226/' /etc/php5/fpm/conf.d/20-xdebug.ini | tee /etc/php5/fpm/conf.d/20-xdebug.ini`

**Comment by mdrovdahl** [comment]
@joshbetz fyi, I just hit this too. Confirmed the fix above works...but, I'm uncertain where the root issue lies.

**Comment by deltamualpha** [comment]
I was looking into this as well. At first I thought it was because the facter fact was wrong... but it turns out that the puppet manifests tries to prevent the ini file from being written to at all: https://github.com/Automattic/vip-quickstart/blob/master/puppet/manifests/sections/php.pp#L36. Looks like the root of this was an older issue: https://github.com/Automattic/vip-quickstart/issues/474
